python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/ft-ddpo" --image_dir "~/ft-images25/" --output_dir "ft-ddpo25" --hub_model_id "jlbaker361/ft-ddpo25" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 15 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/ft-ddpo25/checkpoints"
python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/ft-ddpo" --image_dir "~/ft-images25/" --output_dir "ft-ddpo25" --hub_model_id "jlbaker361/ft-ddpo25" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 15 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/ft-ddpo25/checkpoints"
python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/ft-ddpo" --image_dir "~/ft-images25/" --output_dir "ft-ddpo25" --hub_model_id "jlbaker361/ft-ddpo25" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 15 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/ft-ddpo25/checkpoints"

python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/ft-ddpo25" --image_dir "~/ft-images50/" --output_dir "ft-ddpo50" --hub_model_id "jlbaker361/ft-ddpo50" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 25 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/ft-ddpo50/checkpoints"
python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/ft-ddpo25" --image_dir "~/ft-images50/" --output_dir "ft-ddpo50" --hub_model_id "jlbaker361/ft-ddpo50" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 25 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/ft-ddpo50/checkpoints"
python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/ft-ddpo25" --image_dir "~/ft-images50/" --output_dir "ft-ddpo50" --hub_model_id "jlbaker361/ft-ddpo50" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 25 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/ft-ddpo50/checkpoints"
python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/ft-ddpo25" --image_dir "~/ft-images50/" --output_dir "ft-ddpo50" --hub_model_id "jlbaker361/ft-ddpo50" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 25 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/ft-ddpo50/checkpoints"
python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/ft-ddpo25" --image_dir "~/ft-images50/" --output_dir "ft-ddpo50" --hub_model_id "jlbaker361/ft-ddpo50" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 25 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/ft-ddpo50/checkpoints"

python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/vanilla-ddpo" --image_dir "~/vanilla-images25/" --output_dir "vanilla-ddpo25" --hub_model_id "jlbaker361/vanilla-ddpo25" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 15 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/vanilla-ddpo25/checkpoints"
python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/vanilla-ddpo" --image_dir "~/vanilla-images25/" --output_dir "vanilla-ddpo25" --hub_model_id "jlbaker361/vanilla-ddpo25" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 15 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/vanilla-ddpo25/checkpoints"
python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/vanilla-ddpo" --image_dir "~/vanilla-images25/" --output_dir "vanilla-ddpo25" --hub_model_id "jlbaker361/vanilla-ddpo25" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 15 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/vanilla-ddpo25/checkpoints"

python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/vanilla-ddpo25" --image_dir "~/vanilla-images50/" --output_dir "vanilla-ddpo50" --hub_model_id "jlbaker361/vanilla-ddpo50" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 25 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/vanilla-ddpo50/checkpoints"
python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/vanilla-ddpo25" --image_dir "~/vanilla-images50/" --output_dir "vanilla-ddpo50" --hub_model_id "jlbaker361/vanilla-ddpo50" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 25 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/vanilla-ddpo50/checkpoints"
python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/vanilla-ddpo25" --image_dir "~/vanilla-images50/" --output_dir "vanilla-ddpo50" --hub_model_id "jlbaker361/vanilla-ddpo50" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 25 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/vanilla-ddpo50/checkpoints"
python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/vanilla-ddpo25" --image_dir "~/vanilla-images50/" --output_dir "vanilla-ddpo50" --hub_model_id "jlbaker361/vanilla-ddpo50" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 25 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/vanilla-ddpo50/checkpoints"
python3 ddpo_train_script.py --pretrained_model_name_or_path "jlbaker361/vanilla-ddpo25" --image_dir "~/vanilla-images50/" --output_dir "vanilla-ddpo50" --hub_model_id "jlbaker361/vanilla-ddpo50" --train_gradient_accumulation_steps 4 --train_batch_size 4 --num_epochs 25 --sample_num_steps 30  --sample_batch_size 4  --sample_num_batches_per_epoch 32 --resume_from "~/clipcreate/vanilla-ddpo50/checkpoints"